name: Bug Report
description: Report a bug in AccessLint
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the information below to help us investigate.

  - type: input
    id: version
    attributes:
      label: AccessLint Version
      description: Run `accesslint --version` to get this
      placeholder: "1.3.0"
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: Tier
      options:
        - Free
        - Team
        - Enterprise
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "When I run `accesslint analyze --path ./Sources`, I get..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Xcode version, Swift version
      placeholder: "macOS 15.2, Xcode 16.2, Swift 6.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Output
      description: Paste any error messages or CLI output
      render: shell
    validations:
      required: false
